### ISSUE TITLE
Sync with Press not functional

### ISSUE THREAD

**Issue by alfureu** [kevinpapst/freshrss-fever-api#1] opened 2018-03-15 03:44 UTC
Successfully logged in, however, Press android app cannot sync (it continuously syncs, without success).

**Comment by kevinpapst** [comment] 2018-03-16 09:28
Hey,
I had a chance to debug what Press is actually doing.
The problem is that is not using the API in a specified way. It tries to sync every item ever imported into FreshRSS and its doing that by calling
http://your-freshrss-url/api/fever.php?api&items&since_id=0
and then making its way up by always increasing the id by 50 (50 defined in the Fever API as amount for each item call).
So its requesting
- http://your-freshrss-url/api/fever.php?api&items&since_id=0
- http://your-freshrss-url/api/fever.php?api&items&since_id=50
- http://your-freshrss-url/api/fever.php?api&items&since_id=100
- ...
But the "since_id" is not meant to be some random number, but (according [to this](https://feedafever.com/api)):
> Use the since_id argument with the highest id of locally cached items to request 50 additional items. Repeat until the items array in the response is empty.

So currently the fever.api dumps the same 50 items for every call (as these are the lowest IDs larger than 0/50/100) AND what is much worse in my FreshRSS install in the table `freshrss_user_entry` the lowest id is 1194539700655245 so it would require at least 23.890.794.013.104 calls to reach actuakl items.
We could add some kind of hack to filter such requests and return an empty array of items, but that would lead to other problems. I am not sure what the best way to proceed here is or to accept that Press does use the API in a wrong way. 
While debugging that I tried to let Fiery Feeds load older items and it called the API with an `since_id` = 1651040412 - which is weird as that does not exist at all. And kept on loading that same URL over and over again, until I canceled the call.
 
I see a couple of options:
- hack some logic to prevent such misbehaving apps from abusing the API - but then the API would not work as it should 
- add special files for single apps (as they seem to behave differently)

**Comment by kevinpapst** [comment] 2018-03-16 10:23
Please check the latest README and give it a try.
There is a new `fever-press.php` file that needs to be added to your FreshRSS installation and be used as endpoint in Press. 
You still need to wait quite a while for the initial sync, as Press is going to load ALL articles from your database (but doesn't display them)

**Comment by sgtcoder** [comment] 2018-03-17 06:39
This is a crazy bug Press has! We really need to get Press source code somehow! I wonder why the went out.

**Comment by sgtcoder** [comment] 2018-03-17 06:48
This worked for me and loaded over 1219 unread articles in less than a minute!

Thank you so much for this. I wish we could get Press source code so one of us can maintain it.

**Comment by alfureu** [comment] 2018-04-05 09:23
@codermjb Does this work for you. I cannot make it working ... :(

**Comment by kevinpapst** [comment] 2018-04-05 09:46
And you think we can help without more infos? ;-)
Did you use the fever-press.php as endpoint?

**Comment by kevinpapst** [comment] 2018-05-25 07:45
Closing this issue as this plugin moved to the FreshRSS core. Support for Press was dropped, as it is buggy and not developed any longer.

**Closed as completed by kevinpapst** 2018-05-25 07:45 UTC
